#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <string.h>
#include <time.h>
#include <fcntl.h>
#include <stdlib.h>
#include "util.h"

// function that is responsible to execute the Leaf_Counter executable in the right path (subdirectory). Use piping to get information about the file generated by the Leaf_Counter executable. This file path is then used to accumulate votes.
void execVote_Counter(char *path) {
  int fd[2];
  pipe(fd);
  pid_t childPid = fork();
  if (childPid == 0) {
    close(fd[0]);
    dup2(fd[1], 1);
    char *args[3];
		args[0] = "./Vote_Counter";
		args[1] = path;
		args[2] = NULL;
		execvp(args[0], args);
		perror("Error encountered while executing the process : ");
  } else {
    close(fd[1]);
    wait(NULL);
    char * fileName = (char *) malloc(255*sizeof(char));
    read(fd[0], fileName, 255);
    pid_t childPid2 = fork();
    if (childPid2 == 0) {
      char *args[3];
  		args[0] = "cat";
  		args[1] = trimwhitespace(fileName);
  		args[2] = NULL;
  		execvp(args[0], args);
  		perror("Error encountered while executing the process : ");
    } else {
      wait(NULL);
    }
  }
}

int main(int argc, char **argv){
  // check whether the number of arguments is correct.
	if (argc != 3){
		printf("Usage: %s %s %s\n", argv[0], "relative path (form - /home/dir1/dir2)", "no. of times to run");
		return -1;
	}
  int lim = atoi(argv[2]);
  for (int i = 0; i < lim; i++) {
    execVote_Counter(argv[1]);
  }
  return 1;
}